### ISSUE TITLE
fix quoting of rvm_configure_env in /etc/rvmrc for rvm 1.16

### ISSUE THREAD

**Issue by mpapis** [railsinstaller/railsinstaller-nix#10]

**Comment by thejoecarroll** [comment]
Just ran into this. For the benefit of anyone else who reads this, the workaround for now is to manually fix the file to read as follows (thanks to @mpapis ): https://gist.github.com/0d2c94f0f1b0ddffdf1b

**Comment by Dan2552** [comment]
same problem, cheers for the manual fix

**Comment by jamiescript** [comment]
My file previously read like this...
rvm_configure_env=('LDFLAGS=-L/opt/sm/pkg/active/lib CFLAGS=-I/opt/sm/pkg/active/include CPATH=/opt/sm/pkg/active/include')
Note the single string and not separate strings as suggested in @thejoecarroll gist

Thanks!

**Comment by jimross** [comment]
I am running into this same problem, but as a beginner I am not sure where to go to make these changes.

**Comment by mpapis** [comment]
@jimross run:

``` bash
rvm get head
```

and make sure to read all the outputs, hint: check for red color - it might be hard if you are colorblind.

**Comment by Dan2552** [comment]
@jimross edit /etc/rvmrc with your favorite text editor and replace the contents with the [gist's content](https://gist.github.com/0d2c94f0f1b0ddffdf1b)

**Comment by jimross** [comment]
I ran 'rvm get head' and it gave me the follow which I was able to copy/paste to resolve the issue. Thanks!

``` bash
* WARNING: you have 'rvm_configure_env' in /etc/rvmrc, run the following to fix:

      sudo sed -i'' -e "s#rvm_configure_env=('LDFLAGS=-L/opt/sm/pkg/active/lib CFLAGS=-I/opt/sm/pkg/active/include CPATH=/opt/sm/pkg/active/include')#rvm_configure_env=('LDFLAGS=-L/opt/sm/pkg/active/lib' 'CFLAGS=-I/opt/sm/pkg/active/include' 'CPATH=/opt/sm/pkg/active/include')#" /etc/rvmrc
```

**Comment by jimross** [comment]
Just for future reference, how should I manually navigate to /etc.rvmrc on a Mac?  I've tried searching for it with finder, but that doesn't work.

**Comment by Dan2552** [comment]
you can change your Finder preferences to show your disk in the devices sidebar. Or in terminal you can type `open /etc` or even `open /etc/rvmrc` will just open the file straight in a textedit

**Comment by jimross** [comment]
When I run 'open /etc/rvmrc' I get: The file /etc/rvmrc does not exist.

When I run 'open /etc' I see the etc folder, but no rvmrc file.

**Comment by anderskitson** [comment]
I get the same rvmrc does not esixst

**Comment by mpapis** [comment]
try:

sudo sed -i'' -e "s#rvm_configure_env=('LDFLAGS=-L/opt/sm/pkg/active/lib CFLAGS=-I/opt/sm/pkg/active/include CPATH=/opt/sm/pkg/active/include')#rvm_configure_env=('LDFLAGS=-L/opt/sm/pkg/active/lib' 'CFLAGS=-I/opt/sm/pkg/active/include' 'CPATH=/opt/sm/pkg/active/include')#" /etc/rvmrc

**Comment by Meekohi** [comment]
This bug ruined my day.

**Comment by mpapis** [comment]
@Meekohi I'm working on a new version already, unfortunately I had to restore whole system and it takes more then expected

**Comment by Meekohi** [comment]
Thanks mpapis ;) It happens -- just took me a while to track down this report and make the fix.

**Comment by Bw00d** [comment]
Thanks, that did it for me.

**Comment by tiinus** [comment]
Thanks! Creating /etc/rvmrc (it didn't exist on my machine) and inserting the lines above solved it for me. I'm now running 1.9.3p392!

**Comment by mpapis** [comment]
@tiinus so you do not have Railsinstaller-OSX and it still solves your problem?
