### ISSUE TITLE
OSX Mountain Lion Bad : modifier in $ (/)

### ISSUE THREAD

**Issue by gstoss** [railsinstaller/railsinstaller-nix#12]
I'm having trouble with the post-install step:

Error running sudo su spacewx -c 'bash -c "PATH=\"$PATH:/opt/sm/pkg/active/bin\" git config -- global user.name \"Greg Space\"" : Bad : modifier in $ (/).

What am I doing wrong? I have a previous version of ruby and rails installed on my Mac but no .rvm to blow away as some have suggested. I see no other hiccups during the install process.

**Comment by emachnic** [comment]
Hi @gstoss,

Can you give us any steps to reproduce this issue? What version of OSX are you running?

Thanks.

**Comment by goodburga** [comment]
Having the same issue here - I'm a newbie, but the installer makes it all the way through and then throws this error at the last second.

Any help would be appreicated.

**Comment by emachnic** [comment]
@goodburga 

Can you please give us any steps to reproduce it? What version of OSX are you running?

Thanks!

**Comment by goodburga** [comment]
@emachnic 

I basically downloaded the installer, ran the installer (put in full name and email for git) and then it completes all the way through the end of the progress bar, a dialogue box pops up with another progress bar, and then the error appears. I am running 10.8.2 on a new 2.3 Intel core i7.

Thanks for the help.

**Comment by goodburga** [comment]
Any luck solving this one?

**Comment by mpapis** [comment]
by any chance did you link `bash` to `zsh`? what version of bash is user `spacewx` using:

```
sudo su spacewx -c 'bash --version'
```

**Comment by goodburga** [comment]
For me the version is GNU bash, version 3.2.48(1)-release (x86_64-apple-darwin12)
Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by mpapis** [comment]
this should fix it - but you will have to wait a bit to get it fixes, does it stop your deploy or just prints the message?

**Comment by goodburga** [comment]
I am just getting started with Rails so it doesn't stop a deploy, just stops me from installing right away I guess :)

**Comment by mpapis** [comment]
if it is just a message and the process continues - just ignore it.

if it fails at the warning use "poors man railsinstaller":

```
\curl -L https://get.rvm.io | bash -s -- --rails
```

Although it requires "Command Line Tools for Xcode" from Apple installed before to success.

**Comment by goodburga** [comment]
Ok cool - thanks for all your help - and for Rails Installer!
