### ISSUE TITLE
no more free uploads on github

### ISSUE THREAD

**Issue by mpapis** [railsinstaller/railsinstaller-nix#13]
https://github.com/blog/1302-goodbye-uploads

@drnic  - any proposals?

**Comment by DanielKehoe** [comment]
@mpapis please let know how this gets resolved so I can update my article to include the correct links for newer versions of RailsInstaller:
http://railsapps.github.com/installing-rails.html

**Comment by mpapis** [comment]
moved to S3 => http://railsinstaller.s3.amazonaws.com/list.html

**Comment by DanielKehoe** [comment]
Thanks! Updated the article.

**Comment by mpapis** [comment]
it's not yet 2.0, the ruby-2.0 release will come in two weeks
