### ISSUE TITLE
Installer Taking 5+ Minutes To Open

### ISSUE THREAD

**Issue by richard4339** [railsinstaller/railsinstaller-nix#14]
I'm running OSX 10.8.2 and just grabbed the latest version. After opening the bundled installer app, it prompts me to elevate the installer, the InstallBuilder splash screen opens and goes away, and then it literally sits there for 5 minutes before I get to the select language window. I killed it and reopened a few times, again quitting after 5 minutes. Finally, I rebooted, and the third time I just let it sit. Opened up Activity Monitor, saw that it was using a tiny bit of CPU and 49.7mb of Real Mem. Finally, over five minutes later, I noticed that it had opened in the background, and that the amount of memory it uses had gone up to 52mb. I am positive it had not opened before, because clicking the app in my tray now does bring up this window, whereas nothing happened with it the first few times, or before letting it sit.

I don't think this is normal based on your instructions, so I thought I should report it.

**Comment by mpapis** [comment]
can you provide an image of the window that you mention?

**Comment by richard4339** [comment]
0 minutes in, InstallBuilder splash screen opens then closes almost immediately
![Screen Shot 2012-12-16 at 2 58 33 PM](https://f.cloud.github.com/assets/100804/15769/13449c16-47c5-11e2-8c9c-982a4741050c.png)

5 minutes in, filtered activity monitor shows two processes for RailsInstaller, one local and one as root
![Screen Shot 2012-12-16 at 3 03 31 PM](https://f.cloud.github.com/assets/100804/15770/1e867068-47c5-11e2-995d-1a180ddd39a9.png)

Two minutes later, activity monitor shows no real change
![Screen Shot 2012-12-16 at 3 04 59 PM](https://f.cloud.github.com/assets/100804/15771/24d49fe4-47c5-11e2-9d71-f64b8153c725.png)

10 minutes 9 seconds later the Select Language window opens
![Screen Shot 2012-12-16 at 3 08 42 PM](https://f.cloud.github.com/assets/100804/15772/37912c6a-47c5-11e2-888f-f0c5c0e9ee27.png)

Activity monitor a few seconds later just for reference
![Screen Shot 2012-12-16 at 3 08 49 PM](https://f.cloud.github.com/assets/100804/15773/3cdc61b2-47c5-11e2-89b3-9475abcf8f09.png)

After it finally opens up the language window, it continues as I'd expect it to.

**Comment by mpapis** [comment]
so it took 10 minutes just for the installer to initialize and show the dialog window?

**Comment by richard4339** [comment]
That is correct.

**Comment by mpapis** [comment]
please check with https://rvm.io/src/RailsInstaller-1.0.4-osx-10.6.app.tgz / https://rvm.io/src/RailsInstaller-1.0.4-osx-10.7.app.tgz - it was build with new version of installbuilder, the error could be fixed there already

**Comment by mpapis** [comment]
uploaded to S3 => http://railsinstaller.s3.amazonaws.com/list.html - please let me know if the error still exists
