### ISSUE TITLE
Certain /usr/local/* items have group "rvm"

### ISSUE THREAD

**Issue by cczona** [railsinstaller/railsinstaller-nix#15]
Michel Papis asked me to report this. Certain files & directories under my /usr/local/ have group named "rvm". New files in those directories also get assign group "rvm".

Affected:

/usr/local/.git
/usr/local/CONTRIBUTING.md
/usr/local/man
/usr/local/opt (only contains symlinks to homebrew celler items)
/usr/local/rvm

I'd briefly installed RailsInstaller OSX 4-6 months ago, to evaluate it for instructional usage.  It was uninstalled back then.  My normal setup is RVM + Homebrew.  No known problems with either in the interim.  `brew doctor` reports nothing.

Original discussion in this Twitter thread: 
https://twitter.com/mpapis/status/287716912182460418

**Comment by mpapis** [comment]
please include output of `ls -ld /usr/ocal` and make sure no other place is affected (like after `cd $HOME; touch test.txt`)

**Comment by cczona** [comment]
$ ls -ld /usr/local
drwxr-xr-x  21 cczona  wheel   714B Jan  5 16:21 /usr/local/

$ cd $HOME; touch test.txt; ll test.txt
-rw-r--r--  1 cczona  admin     0B Jan  5 17:03 test.txt

**Comment by mpapis** [comment]
so I assume if you run:

``` bash
cd /usr/ocal
touch test.txt
ll test.txt
```

then this file get's into `rvm` group? (please show the outputs)

**Comment by cczona** [comment]
<code>
$ cd /usr/ocal
$ touch test.txt
$ ll test.txt
-rw-r--r--  1 cczona  wheel     0B Jan  5 18:24 test.txt
</code>

**Comment by cczona** [comment]
(Noticing "ocal" typo. Re-did for "local", same result)

**Comment by mpapis** [comment]
this will be fixed with #17 when we default to `~/.rvm`
