### ISSUE TITLE
Getting error message unon download finishing

### ISSUE THREAD

**Issue by WadeLaw** [railsinstaller/railsinstaller-nix#16]
![Screen shot 2013-03-04 at 7 48 19 PM](https://f.cloud.github.com/assets/3289387/219595/73d8e798-8538-11e2-8092-f9b16a3c9fd4.png)

I am getting this error message once the downloader is finished. It allows me to click finish but it is not showing installed in the terminal when I follow through with that.

**Comment by mpapis** [comment]
it looks like your system is not compatible with the installer (Intel 64bit), it's already reported as #8 - let me know if it's a different problem.

**Comment by WadeLaw** [comment]
I don't know how it could possibly be not compatible I'm running OSX 10.6, Are there any other requirements?

**Comment by mpapis** [comment]
The requirement is Intel 64 bit CPU, check https://discussions.apple.com/thread/3839981?start=0&tstart=0
