### ISSUE TITLE
In need of a OSX 10.9 Mavericks build.

### ISSUE THREAD

**Issue by timbalzer** [railsinstaller/railsinstaller-nix#22]
No rush, just logging the issue in prep for the release.

**Comment by mpapis** [comment]
we can work on it as soon as #19 gets fixed

**Comment by mpapis** [comment]
this can be done earlier, as far as I know mavericks comes with CLT preinstalled so there is no need to embed osx-gcc-installer.

**Comment by MikeMcQuaid** [comment]
Anyone who installs osx-gcc-installer on Mavericks will overwrite system files and break e.g. `clang` putting it in an unrecoverable state without OS reinstall or backup restores. I recommend you fix this.

**Comment by timbalzer** [comment]
Closing this issue as it really isn't relevant anymore. :smile:
