### ISSUE TITLE
Ruby on Rails Installation Error

### ISSUE THREAD

**Issue by saidmaadan** [railsinstaller/railsinstaller-nix#24]
I was able to installed RailsInstaller on my Mac successfully but the issue is when i type rails --version in the Terminal to check if rails has been installed it returns this error: Rails is not currently installed on this system. To get the latest version, simply type: $ sudo gem install rails And I went ahead as its suggested i type sudo gem install rails and it returns another error: ERROR: While executing gem ... (NoMethodError) undefined method `hexdigest' for #OpenSSL::Digest:0x0000010b573a58..
My Mac version is OS X 10.8.5 and i downloaded RailInstaller Mac OSX 10.7 & 10.8 version

**Comment by mpapis** [comment]
restart your cpmputer and rails should appear in your console (unless you have `~/.rvm`)

**Comment by saidmaadan** [comment]
Thx @mpapis! I have restart my computer several times still not working and as per whether i have rvm i think i have rvm installed because i have already installed Ruby (ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin13.0.0) by follow this video guide (http://teamtreehouse.com/library/ruby-foundations/ruby-basics/installing-ruby) before I even install RailsInstaller and i confirmed it i type `rvm list known` this is what i get

``` bash
# MRI Rubies
[ruby-]1.8.6[-p420]
[ruby-]1.8.7[-p374]
[ruby-]1.9.1[-p431]
[ruby-]1.9.2[-p320]
[ruby-]1.9.3[-p448]
[ruby-]2.0.0-p195
[ruby-]2.0.0[-p247]
[ruby-]2.1.0-preview1
[ruby-]2.1.0-head
ruby-head

# GoRuby
goruby

# Topaz
topaz

# TheCodeShop - MRI experimental patches
tcs

# jamesgolick - All around gangster
jamesgolick

# Minimalistic ruby implementation - ISO 30170:2012
mruby[-head]

# JRuby
jruby-1.2.0
jruby-1.3.1
jruby-1.4.0
jruby-1.6.5.1
jruby-1.6.6
jruby-1.6.7.2
jruby-1.6.8
jruby-1.7.4
jruby-1.7.5
jruby[-1.7.6]
jruby-head

# Rubinius
rbx-1.0.1
rbx-1.1.1
rbx-1.2.3
rbx-1.2.4
rbx-2.0.0
rbx[-2.1.1]
rbx-head

# Ruby Enterprise Edition
ree-1.8.6
ree[-1.8.7][-2012.02]

# Kiji
kiji

# MagLev
maglev[-head]
maglev-1.0.0

# Mac OS X Snow Leopard Or Newer
macruby-0.10
macruby-0.11
macruby[-0.12]
macruby-nightly
macruby-head

# Opal
opal

# IronRuby
ironruby[-1.1.3]
ironruby-head
```

**Comment by mpapis** [comment]
`rvm list known` is only a static list for you to get overview what rubies can be used, more important is `rvm list`, also check `ls -ld ~/.rvm`

**Comment by saidmaadan** [comment]
ls -ld ~/.rvm
drwxr-xr-x  30 MS  staff  1020 Nov 28 19:47 /Users/MS/.rvm

**Comment by mpapis** [comment]
this means you have rvm already installed in user directory and it hides the system installation from railsinstaller, we have in plans a new version that will detect user installation and will install ruby and rails to the user installation, unfortunately this takes time.

for now you have two options, either remove the user installation `rm -rf ~/.rvm` or use it to install ruby and rails: `rvm use --install ruby ; gem install rails`

**Comment by saidmaadan** [comment]
@mpapis! Thanks for your help..I really appreciate
