### ISSUE TITLE
Build OSX 10.8 compatible version

### ISSUE THREAD

**Issue by emachnic** [railsinstaller/railsinstaller-nix#3]
Right now, the installer exits when trying to install on OSX 10.8 with the message "The installer was build only for OSX 10.7, exiting now."

This issue is to make sure the build is compatible with the next version of OSX.

**Comment by mpapis** [comment]
I got reports everything from 10.7 should work fine on 10.8, I will build a test version for 10.8 when I get back home, possibly next week.

**Comment by clakeb** [comment]
I am also getting this error on 10.8 golden master.

**Comment by ghost** [comment]
I tried building myself but I got

...
  [✔] ncurses 5.9 ~ dependencies  
  [✔] ncurses 5.9 ~ fetch  

FAIL(paths): Path '/opt/sm/src/ncurses-5.9' does not exist.

**Comment by mpapis** [comment]
@Dan2552 it looks like the url for source was changed, it should work after:

```
sm set update gnu
```

**Comment by cczona** [comment]
Will you be posting a RailsInstaller-osx-10.8.app.tgz now that this issue has been resolved?  Or holding off until the official Mountain Lion release?

**Comment by mpapis** [comment]
I have created a build allowing to run the 10.7 on 10.8, I know most of the components should just work - but I do not have 10.8 to test it, I would appreciate if someone could check it:

https://rvm.io/src/RailsInstaller-1.0.1-osx-10.7.app.tgz

**Comment by ghost** [comment]
Right near the end I get

``` bash
Problem running post-install step. Installation may not complete correctly
Error running sudo su -s $(which bash) dan2552 -c"PATH=\"$PATH:/opt/sm/pkg/active/bin\" git config --global user.name \"Daniel Green\"" : su : illegal option -- s
usage: su [-] [-flm] [login [args]]
```

Otherwise, rails appears to be installed :)

``` bash
-bash-3.2$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin11.4.0]
-bash-3.2$ rails -v
Rails 3.2.6
```

I'm going to do a wipe anyway later and try again on a clean install. I have no idea if anything I've done could be affecting it.

update: same result on a completely clean install

**Comment by mpapis** [comment]
I was checking this on osx system, maybe I missed something, there is other hack I can use, I will try to provide a test build in hour or two

**Comment by mpapis** [comment]
the new builds with fix for the above issue:

https://rvm.io/src/RailsInstaller-1.0.2-osx-10.6.app.tgz
https://rvm.io/src/RailsInstaller-1.0.2-osx-10.7.app.tgz

10.7 should also be working on OSX 10.8

**Comment by ghost** [comment]
I can confirm the new builds work, no errors on installation

**Comment by mpapis** [comment]
@emachnic final confirmation for 10.8 ? or just release to github?

**Comment by emachnic** [comment]
@mpapis I don't have 10.8 so can't test yet. Can either wait until that comes out and I can verify but I don't have a problem releasing if @Dan2552 confirmed it worked

**Comment by sini** [comment]
@emachnic I'm installing it right now -- I'll confirm if it works on 10.8 in a few minutes.

**Comment by sini** [comment]
Confirmed.

**Comment by derfarg** [comment]
Confirmed! https://rvm.io/src/RailsInstaller-1.0.2-osx-10.7.app.tgz works right!

**Comment by cczona** [comment]
1.0.7 is giving me the "This installer was build only for OSX 10.7, exiting now." error with Mountain Lion

**Comment by mpapis** [comment]
the one from railsinstaller.org or:
https://rvm.io/src/RailsInstaller-1.0.2-osx-10.6.app.tgz
https://rvm.io/src/RailsInstaller-1.0.2-osx-10.7.app.tgz
I thought this one fixes it: e791e9f?

**Comment by saeedjabbar** [comment]
The one from railsinstaller.org/ I can confirm it gives that error as well and is not compatible with 10.8.  The rvm.io version does work.

Lion's security has also blocked it by default from installing because its not from the appstore or by an authorized apple dev so you will have to disable this in security.

**Comment by cczona** [comment]
Ah-ha.  EngineYard needs to update their website.

RailsInstaller-1.0.1-osx-10.7.app.tgz (RailsInstaller.org; fails)
RailsInstaller-1.0.2-osx-10.7.app.tgz (rvm.io; success)

**Comment by mpapis** [comment]
I will prepare new build of 1.0.2 with rails 3.2.7 and then release it to railsinstaller.org

**Comment by mpapis** [comment]
new build uploaded and site is updated + deployed

**Comment by sini** [comment]
The download link for 10.7 does not work. The link for 10.6 does.

**Comment by sini** [comment]
Also the Download The Kit button on railsinstaller.org is giving me the windows version, even though the page clearly says for OS X.

**Comment by mpapis** [comment]
maybe there was something wrong with the upload, I have started the upload again, @ 2% now

**Comment by mpapis** [comment]
seams to be fixed after reupload
