### ISSUE TITLE
Use rbenv instead of rvm on OSX

### ISSUE THREAD

**Issue by Soleone** [railsinstaller/railsinstaller-nix#4]
From my experience the new standard ruby version manager seems to be `rbenv` which is considered cleaner and less hacky than `rvm`.

Feel free to mark this ticket as invalid if you don't agree.

**Comment by mpapis** [comment]
Indeed it is invalid, as maintainer of RVM I have in depth knowledge of it and I can provide a lot better support for **Railsinstaller for OSX** with RVM.
